name: Scheduled Daily Posts

# Runs at specific times (UTC times converted from IST)
on:
  schedule:
    - cron: '30 2 * * *'   # 07:30 AM IST
    - cron: '30 8 * * *'   # 01:30 PM IST
    - cron: '30 14 * * *'  # 07:30 PM IST
    - cron: '30 20 * * *'  # 01:30 AM IST
    - cron: '30 5 * * *'   # 10:30 AM IST
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy_requirements.txt
          python -m nltk.downloader vader_lexicon
          python -m spacy download en_core_web_sm

      - name: Run Generate Scheduled Tweets
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_scheduled_tweets.py

      - name: Run Post Scheduled Tweet
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python post_scheduled_tweet.py
