name: Scheduled Frequent Posts

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy_requirements.txt
          python -m nltk.downloader vader_lexicon
          python -m spacy download en_core_web_sm

      - name: Run Generate Tweets
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_scheduled_tweets.py

      - name: Run Post Tweets
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python post_scheduled_tweet.py --count 2
