name: Tech Twitter Automation

on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour instead of every 15 minutes
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Tech Content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy nltk openai google-generativeai
          python -m nltk.downloader vader_lexicon

      - name: Run Generate Tweets (Once Daily)
        if: github.event.schedule == '0 0 * * *'  # Only run at midnight
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_scheduled_tweets.py --max-tweets 50

      - name: Run Post Tweets
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python post_scheduled_tweet.py --count 1

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add scheduled_tweets.json tweet_post_log.txt raw_response_log.txt
          git commit -m "Update scheduled tweets and logs" || echo "No changes to commit"
          git push origin main
