name: Scheduled Daily Posts

on:
  schedule:
    - cron: '30 8 * * *'
    - cron: '30 14 * * *'
    - cron: '30 20 * * *'
    - cron: '30 2 * * *'
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  scheduled-ai-tweet:
    name: Generate & Post Tweet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy_requirements.txt

      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('vader_lexicon')"

      - name: Generate scheduled tweets
        env:
          GOOGLE_GEMINI: ${{ secrets.GOOGLE_GEMINI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_scheduled_tweets.py

      - name: Post scheduled tweet
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python post_scheduled_tweet.py
