name: Test Claude API

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  test-claude:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test_claude_api.py
        run: python test_claude_api.py
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
