name: Daily Tweet Bot

on:
  schedule:
    - cron: '30 3 * * *'  # Scheduled tweet at 9 AM IST (3:30 AM UTC)
  workflow_dispatch:
    inputs:
      custom_prompt:
        description: 'Enter a prompt to tweet immediately'
        required: false
        default: ''

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tweet script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CUSTOM_PROMPT: ${{ github.event.inputs.custom_prompt }}
        run: python main.py
