name: Daily Tweet Bot

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 AM UTC (adjust timezone if needed)
  workflow_dispatch:     # Allows manual trigger too

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # or your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy

    - name: Run the bot script
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python main.py
